apiVersion: v2
name: pterodactyl-panel
description: A Helm chart for pterodactyl.io
type: application
icon: "https://cdn.pterodactyl.io/logos/new/pterodactyl_logo_transparent.png"
version: 0.3.2
appVersion: "v1.11.3"
dependencies:
  - name: mariadb
    version: "11.4.6"
    condition: mariadb.enabled
    repository: "https://charts.bitnami.com/bitnami"
  - name: redis
    version: "17.3.11"
    condition: redis.enabled
    repository: "https://charts.bitnami.com/bitnami"
