global:
  postgresqlEnabled: true
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent

replicaCount: 1

image: ghcr.io/mealie-recipes/mealie:latest

nameOverride: "mealie"
fullnameOverride: "mealie"

probes:
  liveness:
    timeout: 5
  readiness:
    timeout: 5

serviceAccount:
  create: true
  annotations: {}
  name: "smokeping"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: false
  className: "nginx"
  hosts:
    - host: mealie.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: true
  # storageClassName: "longhorn"
  size: "1Gi"
  accessModes:
    - ReadWriteOnce
