{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.claimName) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "xarr.fullname" . }}-data
  labels:
    {{- include "xarr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.data.storageClassName }}
  storageClassName: {{ .Values.persistence.data.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}