{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.claimName) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "xarr.fullname" . }}-config
  labels:
    {{- include "xarr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
{{- end }}