name: penpot
maintainers:
  - name: bancey
    url: https://github.com/bancey/helm-charts
apiVersion: v2
version: 0.1.1
description: Penpot Helm Chart
home: https://github.com/bancey/helm-charts/tree/develop/charts/penpot
icon: https://avatars.githubusercontent.com/u/30179644?s=200&v=4
keywords:
  - kubernetes
  - penpot
  - penpotapp
  - design
sources:
  - https://github.com/penpot/penpot

dependencies:
  - condition: global.postgresqlEnabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.x.x
  - condition: global.redisEnabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 20.x
