replicaCount: 1

image:
  repository: linuxserver/smokeping
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: "smokeping"
fullnameOverride: "smokeping"

serviceAccount:
  create: true
  annotations: {}
  name: "smokeping"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: smokeping.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: true
  storageClassName: "longhorn"
  size: "1Gi"

appConfig:
  probes: |
    https://oss.oetiker.ch/smokeping/doc/smokeping_config.en.html
  targets: |
    https://oss.oetiker.ch/smokeping/doc/smokeping_config.en.html
