{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "smokeping.fullname" . }}
  labels:
    {{- include "smokeping.labels" . | nindent 4 }}
spec:
  accessModes: {{ .Values.persistence.accessModes }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}