{{- if not .Values.appConfig.secretName  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pterodactyl-panel.fullname" . }}-{{ .Values.appConfig.appKey.secretName }}
type: Opaque
stringData:
  APP_KEY: {{ include "pterodactyl-panel.appKey" . }}
{{- end }}