{{- if not .Values.appConfig.secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pterodactyl-panel.fullname" . }}-{{ .Values.appConfig.hashIds.secretName }}
type: Opaque
stringData:
  HASHIDS_SALT: {{ include "pterodactyl-panel.appHashSalt" . }}
  HASHIDS_LENGTH: {{ .Values.appConfig.hashLength | quote }}
{{- end }}