apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pterodactyl-panel.fullname" . }}-{{ .Values.appConfig.hashIds.secretName }}
type: Opaque
stringData:
  HASHIDS_SALT: {{ randAlphaNum 20 | quote }}
  HASHIDS_LENGTH: "8"