{{- if .Values.appConfig.targets }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smokeping.fullname" . }}-targets
data:
  targets: |
    {{ .Values.appConfig.targets | nindent 4 }}
{{- end }}